version: "3"
services:
  calorie-calculator-db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=calorie-calculator-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calorie-calculator
    restart: always

  calorie-calculator:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - calorie-calculator-db
    ports:
      - "8001:8001"
    volumes:
      - ./:/src
    environment:
      - DATABASE_DSN=postgresql://postgres:password@calorie-calculator-db:5432/calorie-calculator
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    restart: always

volumes:
  app-db-data:
