"""update day

Revision ID: 893f4bb1a82b
Revises: cbf116359df3
Create Date: 2022-09-09 20:40:28.127025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893f4bb1a82b'
down_revision = 'cbf116359df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('day_submitter_id_fkey', 'day', type_='foreignkey')
    op.drop_column('day', 'submitter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('submitter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('day_submitter_id_fkey', 'day', 'user', ['submitter_id'], ['id'])
    # ### end Alembic commands ###
