"""update day: add daily calories

Revision ID: 962f7f844218
Revises: 893f4bb1a82b
Create Date: 2022-09-09 21:37:18.338864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962f7f844218'
down_revision = '893f4bb1a82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('daily_calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'daily_calories')
    # ### end Alembic commands ###
