"""date unique

Revision ID: cb9f6be55db5
Revises: 962f7f844218
Create Date: 2022-09-11 17:03:11.856907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9f6be55db5'
down_revision = '962f7f844218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'day', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'day', type_='unique')
    # ### end Alembic commands ###
